import streamlit as st
st.write("Hello World")
st.write("Hello World 2")
st.write("Hello World 3")
st.write("Hello World 4")
st.write("Hello World 5")
st.write("Hello World 6")
st.write("Hello World 7")
st.write("Hello World 8")
st.write("Hello World 9")
st.write("Hello World 10")